version: '3.4'

services:

  css.mysql.data:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ${APPDATA}\Docker\storage\css_mysql:/var/lib/mysql 

  css.web.ui:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
   ports:
     - "4200:80"
     - "8080:443"

  css.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
    depends_on:
      - css.api.admin
      - css.api.setup
      - css.api.scheduling
    ports:
      - "5001:443"
      - "5000:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.auth:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_HTTPS_PORT=5005
     - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
   ports:
     - "5005:443"
     - "5004:80"
   volumes:
     - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.admin:
    depends_on:
      - css.mysql.data
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5007
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_admin
    ports:
      - "5007:443"
      - "5006:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.setup:
    depends_on:
      - css.mysql.data
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5009
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_setup
    ports:
      - "5009:443"
      - "5008:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.scheduling:
    depends_on: 
      - css.mysql.data
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_schedule
    ports:
      - "5003:443"
      - "5002:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.reporting:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_HTTPS_PORT=5011
     - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
     - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css
   ports:
     - "5011:443"
     - "5010:80"
   volumes:
     - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro