version: '3.4'

services:

  scheduling.mysql.data:
    environment:
      MYSQL_ROOT_PASSWORD: cssuser_DEV
    ports:
      - "3306:3306"

  css.web.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4200:80"

  css.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4201:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  css.api.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4202:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  css.api.scheduling:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=server=scheduling.mysql.data;user id=cssuser;password=cssuser_DEV;persistsecurityinfo=True;database=css_dev
    ports:
      - "4203:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  css.api.adminops:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4204:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

