version: '3.4'

services:

  css.mysql.data:
    image: mysql:latest
    container_name: css.mysql.data
  
  css.web.ui:
   image: ${DOCKER_REGISTRY:-cnx}/css.web.ui:${PLATFORM:-linux}-${TAG:-latest} 
   container_name: css.web.ui
   build:
     context: .
     dockerfile: Apps/Css.Web.UI/Dockerfile

  css.api.gateway:
    image: ${DOCKER_REGISTRY:-cnx}/css.api.gateway:${PLATFORM:-linux}-${TAG:-latest}
    container_name: css.api.gateway
    build:
      context: .
      dockerfile: Services/API.Gateway/Css.Api.Gateway/Dockerfile

  css.api.auth:
   image: ${DOCKER_REGISTRY:-cnx}/css.api.auth:${PLATFORM:-linux}-${TAG:-latest}
   container_name: css.api.auth
   build:
     context: .
     dockerfile: Services/API.Identity/Css.Api.Auth/Dockerfile

  css.api.admin:
    image: ${DOCKER_REGISTRY:-cnx}/css.api.admin:${PLATFORM:-linux}-${TAG:-latest}
    container_name: css.api.admin
    build:
      context: .
      dockerfile: Services/API.Admin/Css.Api.Admin/Dockerfile

  css.api.setup:
    image: ${DOCKER_REGISTRY:-cnx}/css.api.setup:${PLATFORM:-linux}-${TAG:-latest}
    container_name: css.api.setup
    build:
      context: .
      dockerfile: Services/Api.Setup/Css.Api.Setup/Dockerfile

  css.api.scheduling:
    image: ${DOCKER_REGISTRY:-cnx}/css.api.scheduling:${PLATFORM:-linux}-${TAG:-latest}
    container_name: css.api.scheduling
    build:
      context: .
      dockerfile: Services/API.Scheduling/Css.Api.Scheduling/Dockerfile

  css.api.reporting:
   image: ${DOCKER_REGISTRY:-cnx}/css.api.reporting:${PLATFORM:-linux}-${TAG:-latest}
   build:
     context: .
     dockerfile: Services/API.Reporting/Css.Api.Reporting/Dockerfile