version: '3.4'

services:

  css.mysql.data:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ${APPDATA}\Docker\storage\css_mysql:/var/lib/mysql 

  css.mongo1:
    hostname: css.mongo1
    volumes:
      - ${APPDATA}\Docker\storage\css.mongo1\db:/data/db
      - ${APPDATA}\Docker\storage\css.mongo1\configdb:/data/configdb
    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  css.mongo2:
    hostname: css.mongo2
    volumes:
      - ${APPDATA}\Docker\storage\css.mongo2\db:/data/db
      - ${APPDATA}\Docker\storage\css.mongo2\configdb:/data/configdb
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
   
  css.mongo3:
    hostname: css.mongo3
    volumes:
      - ${APPDATA}\Docker\storage\css.mongo3\db:/data/db
      - ${APPDATA}\Docker\storage\css.mongo3\configdb:/data/configdb
    expose:
      - 27017
    ports:
      - 30003:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  css.mongo.cluster:
    depends_on:
       - "css.mongo1"
       - "css.mongo2"
       - "css.mongo3"
    links:
       - css.mongo1:css.mongo1
       - css.mongo2:css.mongo2
       - css.mongo2:css.mongo3
    volumes:
      - ./scripts:/scripts
    environment: 
      - MONGO1=css.mongo1
      - MONGO2=css.mongo2
      - MONGO3=css.mongo3
      - RS=rs0
    entrypoint: [ "/scripts/mongo-setup.sh" ]

  css.service.bus:
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  css.web.ui:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
   ports:
     - "4200:80"
     - "8080:443"

  css.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
    depends_on:
      - css.api.admin
      - css.api.setup
      - css.api.scheduling
      - css.api.reporting
    ports:
      - "5001:443"
      - "5000:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.auth:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_HTTPS_PORT=5005
     - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
   ports:
     - "5005:443"
     - "5004:80"
   volumes:
     - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.admin:
    depends_on:
      - css.mysql.data
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5007
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_admin
    ports:
      - "5007:443"
      - "5006:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.setup:
    depends_on:
      - css.mysql.data
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5009
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_setup
      - ConnectionStrings__ServiceBus=rabbitmq://guest:guest@css.service.bus/
    ports:
      - "5009:443"
      - "5008:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.scheduling:
    depends_on: 
      - css.mongo1
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
      - ConnectionStrings__Database=server=css.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css_schedule
      - MongoDbSettings__ConnectionStrings=mongodb://mongo1:30001
      - MongoDbSettings__DatabaseName=css_dev
      - ConnectionStrings__ServiceBus=rabbitmq://guest:guest@css.service.bus/
    ports:
      - "5003:443"
      - "5002:80"
    volumes:
      - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro

  css.api.reporting:
   depends_on: 
      - css.mongo1
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_HTTPS_PORT=5011
     - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
     - MongoDbSettings__ConnectionStrings=mongodb://mongo1:30001
     - MongoDbSettings__DatabaseName=css_dev
   ports:
     - "5011:443"
     - "5010:80"
   volumes:
     - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
  
  css.api.job:
   environment:
     - ASPNETCORE_ENVIRONMENT=Local
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_HTTPS_PORT=5013
     - ASPNETCORE_Kestrel__Certificates__Default__Password=cnxcss
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/css.pfx
   ports:
     - "5013:443"
     - "5012:80"
   volumes:
     - ${APPDATA}\ASP.NET\Https\:/root/.aspnet/https:ro
     - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro