version: '3.4'

services:

  scheduling.mysql.data:
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  css.web.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4200:80"
      - "8080:443"

  css.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - css.api.auth
      - css.api.admin
      - css.api.setup
      - css.api.scheduling
      - css.api.reporting
    ports:
      - "4201:80"
      - "8081:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  css.api.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "4202:80"
      - "8082:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  css.api.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=server=scheduling.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css
    ports:
      - "4203:80"
      - "8083:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  css.api.setup:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=server=scheduling.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css
    ports:
      - "4204:80"
      - "8084:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  css.api.scheduling:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=server=scheduling.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css
    ports:
      - "4205:80"
      - "8085:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  css.api.reporting:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=server=scheduling.mysql.data;user id=root;password=root;persistsecurityinfo=True;database=css
    ports:
      - "4206:80"
      - "8086:443"
    volumes:
      - ~/.aspnet/https:/https:ro
