//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Css.Api.Core.EventBus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MassTransitConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MassTransitConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Css.Api.Core.EventBus.MassTransitConstants", typeof(MassTransitConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.
        /// </summary>
        public static string ClientCommandQueue {
            get {
                return ResourceManager.GetString("ClientCommandQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.#.
        /// </summary>
        public static string ClientCommandQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientCommandQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.create.client.
        /// </summary>
        public static string ClientCreateCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.create.failed.
        /// </summary>
        public static string ClientCreateFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.create.success.
        /// </summary>
        public static string ClientCreateSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.
        /// </summary>
        public static string ClientEventQueue {
            get {
                return ResourceManager.GetString("ClientEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.#.
        /// </summary>
        public static string ClientEventQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientEventQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.
        /// </summary>
        public static string ClientExchange {
            get {
                return ResourceManager.GetString("ClientExchange", resourceCulture);
            }
        }
    }
}
