//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Css.Api.Core.EventBus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MassTransitConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MassTransitConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Css.Api.Core.EventBus.MassTransitConstants", typeof(MassTransitConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.
        /// </summary>
        public static string ClientCommandQueue {
            get {
                return ResourceManager.GetString("ClientCommandQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.#.
        /// </summary>
        public static string ClientCommandQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientCommandQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.create.client.
        /// </summary>
        public static string ClientCreateCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.create.failed.
        /// </summary>
        public static string ClientCreateFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.create.success.
        /// </summary>
        public static string ClientCreateSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientCreateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.delete.client.
        /// </summary>
        public static string ClientDeleteCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientDeleteCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.delete.failed.
        /// </summary>
        public static string ClientDeleteFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientDeleteFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.delete.success.
        /// </summary>
        public static string ClientDeleteSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientDeleteSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.
        /// </summary>
        public static string ClientEventQueue {
            get {
                return ResourceManager.GetString("ClientEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.#.
        /// </summary>
        public static string ClientEventQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientEventQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.
        /// </summary>
        public static string ClientExchange {
            get {
                return ResourceManager.GetString("ClientExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.commands.
        /// </summary>
        public static string ClientLOBCommandQueue {
            get {
                return ResourceManager.GetString("ClientLOBCommandQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.commands.#.
        /// </summary>
        public static string ClientLOBCommandQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientLOBCommandQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.commands.create.clientlob.
        /// </summary>
        public static string ClientLOBCreateCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBCreateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.create.failed.
        /// </summary>
        public static string ClientLOBCreateFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBCreateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.create.success.
        /// </summary>
        public static string ClientLOBCreateSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBCreateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.commands.delete.clientlob.
        /// </summary>
        public static string ClientLOBDeleteCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBDeleteCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.delete.failed.
        /// </summary>
        public static string ClientLOBDeleteFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBDeleteFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.delete.success.
        /// </summary>
        public static string ClientLOBDeleteSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBDeleteSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.
        /// </summary>
        public static string ClientLOBEventQueue {
            get {
                return ResourceManager.GetString("ClientLOBEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.#.
        /// </summary>
        public static string ClientLOBEventQueueBindingPattern {
            get {
                return ResourceManager.GetString("ClientLOBEventQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.
        /// </summary>
        public static string ClientLOBExchange {
            get {
                return ResourceManager.GetString("ClientLOBExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.commands.update.clientlob.
        /// </summary>
        public static string ClientLOBUpdateCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBUpdateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.update.failed.
        /// </summary>
        public static string ClientLOBUpdateFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBUpdateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.clientlob.events.update.success.
        /// </summary>
        public static string ClientLOBUpdateSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientLOBUpdateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.commands.update.client.
        /// </summary>
        public static string ClientUpdateCommandRouteKey {
            get {
                return ResourceManager.GetString("ClientUpdateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.update.failed.
        /// </summary>
        public static string ClientUpdateFailedRouteKey {
            get {
                return ResourceManager.GetString("ClientUpdateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.client.events.update.success.
        /// </summary>
        public static string ClientUpdateSuccessRouteKey {
            get {
                return ResourceManager.GetString("ClientUpdateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.commands.
        /// </summary>
        public static string SkillGroupCommandQueue {
            get {
                return ResourceManager.GetString("SkillGroupCommandQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.commands.#.
        /// </summary>
        public static string SkillGroupCommandQueueBindingPattern {
            get {
                return ResourceManager.GetString("SkillGroupCommandQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.commands.create.skillgroup.
        /// </summary>
        public static string SkillGroupCreateCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupCreateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.create.failed.
        /// </summary>
        public static string SkillGroupCreateFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupCreateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.create.success.
        /// </summary>
        public static string SkillGroupCreateSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupCreateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.commands.delete.skillgroup.
        /// </summary>
        public static string SkillGroupDeleteCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupDeleteCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.delete.failed.
        /// </summary>
        public static string SkillGroupDeleteFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupDeleteFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.delete.success.
        /// </summary>
        public static string SkillGroupDeleteSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupDeleteSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.
        /// </summary>
        public static string SkillGroupEventQueue {
            get {
                return ResourceManager.GetString("SkillGroupEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.#.
        /// </summary>
        public static string SkillGroupEventQueueBindingPattern {
            get {
                return ResourceManager.GetString("SkillGroupEventQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.
        /// </summary>
        public static string SkillGroupExchange {
            get {
                return ResourceManager.GetString("SkillGroupExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.commands.update.skillgroup.
        /// </summary>
        public static string SkillGroupUpdateCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupUpdateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.update.failed.
        /// </summary>
        public static string SkillGroupUpdateFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupUpdateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skillgroup.events.update.success.
        /// </summary>
        public static string SkillGroupUpdateSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillGroupUpdateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.commands.
        /// </summary>
        public static string SkillTagCommandQueue {
            get {
                return ResourceManager.GetString("SkillTagCommandQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.commands.#.
        /// </summary>
        public static string SkillTagCommandQueueBindingPattern {
            get {
                return ResourceManager.GetString("SkillTagCommandQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.commands.create.skilltag.
        /// </summary>
        public static string SkillTagCreateCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillTagCreateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.create.failed.
        /// </summary>
        public static string SkillTagCreateFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillTagCreateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.create.success.
        /// </summary>
        public static string SkillTagCreateSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillTagCreateSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.commands.delete.skilltag.
        /// </summary>
        public static string SkillTagDeleteCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillTagDeleteCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.delete.failed.
        /// </summary>
        public static string SkillTagDeleteFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillTagDeleteFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.delete.success.
        /// </summary>
        public static string SkillTagDeleteSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillTagDeleteSuccessRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.
        /// </summary>
        public static string SkillTagEventQueue {
            get {
                return ResourceManager.GetString("SkillTagEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.#.
        /// </summary>
        public static string SkillTagEventQueueBindingPattern {
            get {
                return ResourceManager.GetString("SkillTagEventQueueBindingPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.
        /// </summary>
        public static string SkillTagExchange {
            get {
                return ResourceManager.GetString("SkillTagExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.commands.update.skilltag.
        /// </summary>
        public static string SkillTagUpdateCommandRouteKey {
            get {
                return ResourceManager.GetString("SkillTagUpdateCommandRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.update.failed.
        /// </summary>
        public static string SkillTagUpdateFailedRouteKey {
            get {
                return ResourceManager.GetString("SkillTagUpdateFailedRouteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css.skilltag.events.update.success.
        /// </summary>
        public static string SkillTagUpdateSuccessRouteKey {
            get {
                return ResourceManager.GetString("SkillTagUpdateSuccessRouteKey", resourceCulture);
            }
        }
    }
}
