//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Css.Api.Reporting.Business.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Css.Api.Reporting.Business.Data.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export of agent info has been disabled for the requested system. Kindly contact system administrator..
        /// </summary>
        internal static string AgentExportNotAllowed {
            get {
                return ResourceManager.GetString("AgentExportNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is a mandatory field, expected value is a alphanumeric string other than 0.
        /// </summary>
        internal static string AgentIdMandatory {
            get {
                return ResourceManager.GetString("AgentIdMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Agent id - couldn&apos;t find the agent details in our system.
        /// </summary>
        internal static string AgentNotFound {
            get {
                return ResourceManager.GetString("AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch {0} encountered an error during processing. Details - {1}.
        /// </summary>
        internal static string BatchProcessingError {
            get {
                return ResourceManager.GetString("BatchProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any files to read in the requested directory.
        /// </summary>
        internal static string EmptyFTPDirectory {
            get {
                return ResourceManager.GetString("EmptyFTPDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate the export file for the requested date(s).
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedules available for the requested date(s).
        /// </summary>
        internal static string ExportNoData {
            get {
                return ResourceManager.GetString("ExportNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire date is a mandatory field, expected a valid date in the format yyyyMMdd.
        /// </summary>
        internal static string HireDateMandatory {
            get {
                return ResourceManager.GetString("HireDateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid agent categories - {0}.
        /// </summary>
        internal static string InvalidAgentCategories {
            get {
                return ResourceManager.GetString("InvalidAgentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} category value, expected value is a date in the format - yyyyMMdd.
        /// </summary>
        internal static string InvalidAgentCategoryDate {
            get {
                return ResourceManager.GetString("InvalidAgentCategoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} category value, expected value is a numeric value between {1} and {2}.
        /// </summary>
        internal static string InvalidAgentCategoryNumeric {
            get {
                return ResourceManager.GetString("InvalidAgentCategoryNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data source specified for key - &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidDataSource {
            get {
                return ResourceManager.GetString("InvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data target specified for key - &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidDataTarget {
            get {
                return ResourceManager.GetString("InvalidDataTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime - &apos;{0}&apos;  format supported &apos;yyyy-MM-dd HH:mm&apos;.
        /// </summary>
        internal static string InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedules do not fall within -1 to +1 days of the schedule date.
        /// </summary>
        internal static string InvalidDateTimeSchedule {
            get {
                return ResourceManager.GetString("InvalidDateTimeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end date &apos;{0}&apos; specified for schedule starting at &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidEndDateTime {
            get {
                return ResourceManager.GetString("InvalidEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU details for {0} is missing in the system.
        /// </summary>
        internal static string InvalidMU {
            get {
                return ResourceManager.GetString("InvalidMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request parameters. Kindly specify atleast one agent id and a valid combination of start &amp; end dates.
        /// </summary>
        internal static string InvalidQueryParamsCNX1 {
            get {
                return ResourceManager.GetString("InvalidQueryParamsCNX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schedule date, format supported - &apos;yyyy-MM-dd&apos;.
        /// </summary>
        internal static string InvalidScheduleDate {
            get {
                return ResourceManager.GetString("InvalidScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activity code - &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidSchedulingCode {
            get {
                return ResourceManager.GetString("InvalidSchedulingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in senDate, expected value is a valid date combination of day, month and year.
        /// </summary>
        internal static string InvalidSenDate {
            get {
                return ResourceManager.GetString("InvalidSenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in senExt, expected value is a numeric value between 1 and 9999.
        /// </summary>
        internal static string InvalidSenExt {
            get {
                return ResourceManager.GetString("InvalidSenExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source specified for key - &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidSource {
            get {
                return ResourceManager.GetString("InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target specified for key - &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidTarget {
            get {
                return ResourceManager.GetString("InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timezone - the timezone specified is an invalid IANA timezone. Please refer &apos;https://en.wikipedia.org/wiki/List_of_tz_database_time_zones&apos; .
        /// </summary>
        internal static string InvalidTimezone {
            get {
                return ResourceManager.GetString("InvalidTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping not found for key - &apos;{0}&apos;.
        /// </summary>
        internal static string MappingNotFound {
            get {
                return ResourceManager.GetString("MappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU is a mandatory field, cannot be null or empty for new CSS agents.
        /// </summary>
        internal static string MuMandatory {
            get {
                return ResourceManager.GetString("MuMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a mandatory information for all new CSS agents.
        /// </summary>
        internal static string NameMandatory {
            get {
                return ResourceManager.GetString("NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently no agents are provisioned for EStart.
        /// </summary>
        internal static string NoAgentsEStartProvisioned {
            get {
                return ResourceManager.GetString("NoAgentsEStartProvisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedules present between &apos;{0}&apos; and &apos;{1}&apos; for the agent.
        /// </summary>
        internal static string NoSchedulesPresent {
            get {
                return ResourceManager.GetString("NoSchedulesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedules to update.
        /// </summary>
        internal static string NoSchedulesToUpdate {
            get {
                return ResourceManager.GetString("NoSchedulesToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedule starting at {0} and ending at {1} overlaps an existing schedule on {2}.
        /// </summary>
        internal static string OverlappingExistingSchedules {
            get {
                return ResourceManager.GetString("OverlappingExistingSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping schedules exists for the schedule on &apos;{0}&apos;.
        /// </summary>
        internal static string OverlappingSchedules {
            get {
                return ResourceManager.GetString("OverlappingSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to map the route - &apos;{0}&apos;.
        /// </summary>
        internal static string RouteNotFound {
            get {
                return ResourceManager.GetString("RouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not permitted to update a schedule for a past date.
        /// </summary>
        internal static string ScheduleUpdateNotAllowed {
            get {
                return ResourceManager.GetString("ScheduleUpdateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN is a mandatory field, expected value is a alphanumeric string other than 0.
        /// </summary>
        internal static string SsnMandatory {
            get {
                return ResourceManager.GetString("SsnMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO is a mandatory field, expected value is a valid email address.
        /// </summary>
        internal static string SsoMandatory {
            get {
                return ResourceManager.GetString("SsoMandatory", resourceCulture);
            }
        }
    }
}
